### ISSUE TITLE
ERROR_USER가 empty 상태일 경우 에러 메시지가 표시되지 않도록 수정해야할 필요성

### ISSUE THREAD

**Issue by wizleysw** [onsoim/SAG.bot#4]
https://github.com/onsoim/SAG.bot/blob/90f2b7bae196680f2988e1fcc606da338da8c245/src/bot_discord.py#L22

**Comment by onsoim** [comment]
모든 유저가 정상적으로 처리되는 경우, 에러메시지가 출력 되지 않도록 수정하였습니다.
